// <auto-generated />
using Eventos.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Eventos.DAL.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Eventos.DAL.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data");

                    b.Property<int>("FaixaEtaria");

                    b.Property<TimeSpan>("HoraFim");

                    b.Property<TimeSpan>("HoraInicio");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("OpenBar");

                    b.Property<int>("QuantidadeDeAmbientes");
					
					b.Property<string>("FaixaEtaria");

                    b.Property<int>("MaximoIngressos")
                        .IsRequired();

                    b.Property<int>("IngressosVendidos")
                        .IsRequired();

                    b.Property<string>("QuantidadeIngressos");

                    b.Property<string>("NomeParticipante")
                       .IsRequired();

                    b.Property<string>("Email");

                    b.HasKey("IdEvento");

                    b.ToTable("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
